Lab\_05
================
NickyNie
9/24/2021

``` r
library(data.table)
library(dplyr)
```

## Preprocessing data

``` r
# Download the data
met <- fread("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz")
stations <- fread("ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-history.csv")
stations[, USAF := as.integer(USAF)]
```

    ## Warning in eval(jsub, SDenv, parent.frame()): 强制改变过程中产生了NA

``` r
# Dealing with NAs and 999999
stations[, USAF   := fifelse(USAF == 999999, NA_integer_, USAF)]
stations[, CTRY   := fifelse(CTRY == "", NA_character_, CTRY)]
stations[, STATE  := fifelse(STATE == "", NA_character_, STATE)]

# Selecting the three relevant columns, and keeping unique records
stations <- unique(stations[, list(USAF, CTRY, STATE)])

# Dropping NAs
stations <- stations[!is.na(USAF)]

# Removing duplicates
stations[, n := 1:.N, by = .(USAF)]
stations <- stations[n == 1,][, n := NULL]
```

## Merging data

``` r
met <- merge(
  x     = met,
  y     = stations,
  by.x  = "USAFID",
  by.y  = "USAF",
  all.x = TRUE,
  all.y = FALSE
)
```

# Question 1

``` r
station_avg <- met[,.(
  temp = mean(temp, na.rm = TRUE),
  wind.sp = mean(wind.sp, na.rm = TRUE),
  atm.press = mean(atm.press, na.rm = TRUE),
  lon_avg = mean(lon, na.rm = TRUE),
  lat_avg = mean(lat, na.rm = TRUE)
), by = USAFID]
```

identify the median per variable

``` r
medians <- station_avg[,.(
  temp_50 = quantile(temp, probs = 0.5, na.rm = TRUE),
  wind.sp_50 = quantile(wind.sp, probs = 0.5, na.rm = TRUE),
  atm.press_50 = quantile(atm.press, probs = 0.5, na.rm = TRUE)
) ]

medians
```

    ##     temp_50 wind.sp_50 atm.press_50
    ## 1: 23.68406   2.461838     1014.691

find stations that are the closest to these (hint: `which.min()`)

``` r
station_avg[, temp_dist := abs(temp - medians$temp_50)]
median_temp_station <- station_avg[order(temp_dist)][1]
median_temp_station
```

    ##    USAFID     temp  wind.sp atm.press lon_avg lat_avg   temp_dist
    ## 1: 720458 23.68173 1.209682       NaN -82.637  37.751 0.002328907

The median temperature station is 720458

``` r
station_avg[, wind.sp_dist := abs(wind.sp - medians$wind.sp_50)]
median_wind.sp_station <-station_avg[order(wind.sp_dist)][1]
median_wind.sp_station 
```

    ##    USAFID     temp  wind.sp atm.press lon_avg lat_avg temp_dist wind.sp_dist
    ## 1: 720929 17.43278 2.461838       NaN -91.981  45.506  6.251284            0

The median wind speed station is 720929

``` r
station_avg[, atm.press_dist := abs(atm.press - medians$atm.press_50)]
median_atm.press_station <- station_avg[order(atm.press_dist)][1]
median_atm.press_station
```

    ##    USAFID     temp  wind.sp atm.press   lon_avg lat_avg temp_dist wind.sp_dist
    ## 1: 722238 26.13978 1.472656  1014.691 -85.66667 31.3499  2.455719    0.9891817
    ##    atm.press_dist
    ## 1:   0.0005376377

The median atmospheric pressure station is 722238

# Question 2

recover the state variable, by MERGING

``` r
station_avg <- merge(
  x = station_avg, 
  y = stations, 
  by.x = "USAFID", 
  by.y = "USAF", 
  all.x = TRUE, 
  all.y = FALSE
  )
```

compute the medians per state

``` r
station_avg[, temp_50 := quantile(temp, probs = 0.5, na.rm = TRUE),by = STATE]
station_avg[, wind.sp_50 := quantile(wind.sp, probs = 0.5, na.rm = TRUE),by = STATE]
```

``` r
station_avg[, eudist:= sqrt(
  (temp - temp_50)^2+(wind.sp - wind.sp_50)^2
)]
station_avg
```

    ##       USAFID     temp  wind.sp atm.press   lon_avg  lat_avg temp_dist
    ##    1: 690150 33.18763 3.483560  1010.379 -116.1658 34.29982 9.5035752
    ##    2: 720110 31.22003 2.138348       NaN  -98.6620 30.78400 7.5359677
    ##    3: 720113 23.29317 2.470298       NaN  -83.1780 42.54300 0.3908894
    ##    4: 720120 27.01922 2.504692       NaN  -80.6998 32.21746 3.3351568
    ##    5: 720137 21.88823 1.979335       NaN  -88.4190 41.42500 1.7958292
    ##   ---                                                                
    ## 1591: 726777 19.15492 4.673878  1014.299 -104.2501 46.35792 4.5291393
    ## 1592: 726797 18.78980 2.858586  1014.902 -111.1600 45.78795 4.8942607
    ## 1593: 726798 19.47014 4.445783  1014.072 -110.4400 45.69800 4.2139153
    ## 1594: 726810 25.03549 3.039794  1011.730 -116.2390 43.56700 1.3514356
    ## 1595: 726813 23.47809 2.435372  1012.315 -116.6331 43.64963 0.2059716
    ##       wind.sp_dist atm.press_dist CTRY STATE  temp_50 wind.sp_50     eudist
    ##    1:  1.021721847      4.3124708   US    CA 22.66268   2.565445 10.5649277
    ##    2:  0.323490383            NaN   US    TX 29.75188   3.413737  1.9447578
    ##    3:  0.008459788            NaN   US    MI 20.51970   2.273423  2.7804480
    ##    4:  0.042854372            NaN   US    SC 25.80545   1.696119  1.4584280
    ##    5:  0.482502805            NaN   US    IL 22.43194   2.237622  0.6019431
    ##   ---                                                                      
    ## 1591:  2.212040085      0.3920955   US    MT 19.15492   4.151737  0.5221409
    ## 1592:  0.396747923      0.2106085   US    MT 19.15492   4.151737  1.3437090
    ## 1593:  1.983945197      0.6195467   US    MT 19.15492   4.151737  0.4310791
    ## 1594:  0.577955642      2.9607085   US    ID 20.56798   2.568944  4.4922623
    ## 1595:  0.026465595      2.3759601   US    ID 20.56798   2.568944  2.9131751

Find the most representative station per state

``` r
station_state <- station_avg[ , .SD[which.min(eudist)], by = STATE]
station_state
```

    ##     STATE USAFID     temp  wind.sp atm.press    lon_avg  lat_avg temp_dist
    ##  1:    CA 722970 22.76040 2.325982  1012.710 -118.14652 33.81264 0.9236572
    ##  2:    TX 722598 29.81293 3.521417       NaN  -96.83600 32.96900 6.1288732
    ##  3:    MI 725395 20.44096 2.357275  1015.245  -84.46697 42.26697 3.2431039
    ##  4:    SC 723107 25.95831 1.599275       NaN  -80.20900 33.58700 2.2742552
    ##  5:    IL 722076 22.34403 2.244115       NaN  -87.59982 40.19995 1.3400341
    ##  6:    MO 720479 24.14775 2.508153       NaN  -94.01700 36.90000 0.4636885
    ##  7:    AR 722054 26.58944 1.707136  1014.127  -90.23400 35.13500 2.9053841
    ##  8:    OR 720202 17.16329 1.828437       NaN -123.81700 45.41700 6.5207664
    ##  9:    WA 720254 19.24684 1.268571       NaN -122.98300 46.68276 4.4372238
    ## 10:    GA 722197 26.70404 1.544133  1015.574  -84.56702 33.35501 3.0199790
    ## 11:    MN 726553 19.67552 2.393582       NaN  -95.71000 44.96900 4.0085430
    ## 12:    AL 722286 26.35793 1.675828  1014.909  -87.61600 33.21200 2.6738730
    ## 13:    IN 724386 22.32575 2.243013  1014.797  -86.93700 40.41200 1.3583049
    ## 14:    NC 720864 24.82394 1.612864       NaN  -77.54700 35.93700 1.1398816
    ## 15:    VA 724006 24.31662 1.650539       NaN  -76.32100 36.66600 0.6325625
    ## 16:    IA 725464 21.37948 2.679227       NaN  -93.02200 41.67400 2.3045767
    ## 17:    PA 725204 21.87141 1.825605       NaN  -80.39819 40.76821 1.8126473
    ## 18:    NE 725565 21.86100 3.098367  1015.068  -97.34964 41.43378 1.8230630
    ## 19:    ID 725867 20.81272 2.702517  1012.802 -113.76605 42.54201 2.8713440
    ## 20:    WI 726413 18.94233 2.028610       NaN  -88.13280 43.41720 4.7417341
    ## 21:    WV 720328 21.94820 1.617823       NaN  -80.27400 39.00000 1.7358610
    ## 22:    MD 722218 24.89883 1.883499       NaN  -76.03288 38.53325 1.2147717
    ## 23:    AZ 722745 30.31538 3.307632  1010.144 -110.88300 32.16695 6.6313167
    ## 24:    OK 720625 27.06188 3.865717       NaN  -97.35000 36.75000 3.3778197
    ## 25:    WY 726654 19.85844 3.775443  1014.107 -106.72100 44.38100 3.8256192
    ## 26:    LA 722041 27.84758 1.476664       NaN  -90.26100 29.44500 4.1635250
    ## 27:    KY 720448 23.52994 1.604905       NaN  -84.77000 37.57800 0.1541178
    ## 28:    FL 722011 27.56952 2.674074  1016.063  -81.43700 28.29000 3.8854636
    ## 29:    CO 724699 21.94228 2.844072       NaN -105.11607 39.90067 1.7417815
    ## 30:    OH 724295 21.97211 2.803524  1015.742  -83.84000 39.84000 1.7119534
    ## 31:    NJ 724090 23.47238 2.148606  1015.095  -74.35016 40.03300 0.2116829
    ## 32:    NM 723658 24.94447 3.569281  1013.917 -108.22900 36.74400 1.2604141
    ## 33:    KS 724550 24.14958 3.449278  1013.315  -96.76687 39.05022 0.4655163
    ## 34:    ND 720911 18.34248 3.940128       NaN  -98.01800 46.94196 5.3415810
    ## 35:    VT 726115 18.60548 1.101301  1014.985  -72.51800 43.34400 5.0785811
    ## 36:    MS 722358 26.54093 1.747426  1014.722  -90.47100 31.18298 2.8568706
    ## 37:    CT 725087 22.57539 2.126514  1014.534  -72.65098 41.73601 1.1086682
    ## 38:    NV 724885 24.78430 2.600266  1013.855 -118.71577 39.41700 1.1002416
    ## 39:    UT 725750 24.23571 3.040962  1011.521 -112.01100 41.19600 0.5516551
    ## 40:    SD 726590 19.95928 3.550722  1014.284  -98.41344 45.44377 3.7247800
    ## 41:    TN 720974 24.71645 1.483411       NaN  -86.06600 35.17800 1.0323860
    ## 42:    NY 724988 20.44142 2.394383  1016.233  -77.71300 42.57100 3.2426385
    ## 43:    RI 725079 22.27697 2.583469  1014.620  -71.28300 41.53300 1.4070879
    ## 44:    MA 725088 21.20391 2.773018  1013.718  -70.91800 42.58400 2.4801457
    ## 45:    DE 724180 24.56026 2.752929  1015.046  -75.60600 39.67400 0.8761984
    ## 46:    NH 726116 19.23920 1.465766  1013.840  -72.30500 43.62600 4.4448592
    ## 47:    ME 726077 18.49969 2.337241  1014.475  -68.36677 44.45000 5.1843701
    ## 48:    MT 726798 19.47014 4.445783  1014.072 -110.44004 45.69800 4.2139153
    ##     STATE USAFID     temp  wind.sp atm.press    lon_avg  lat_avg temp_dist
    ##     wind.sp_dist atm.press_dist CTRY  temp_50 wind.sp_50     eudist
    ##  1:   0.13585606     1.98090662   US 22.66268   2.565445 0.25863745
    ##  2:   1.05957887            NaN   US 29.75188   3.413737 0.12378522
    ##  3:   0.10456335     0.55414742   US 20.51970   2.273423 0.11503023
    ##  4:   0.86256290            NaN   US 25.80545   1.696119 0.18095742
    ##  5:   0.21772293            NaN   US 22.43194   2.237622 0.08815689
    ##  6:   0.04631522            NaN   US 23.95109   2.453547 0.20409808
    ##  7:   0.75470197     0.56429267   US 26.24296   1.938625 0.41669854
    ##  8:   0.63340128            NaN   US 17.98061   2.011436 0.83755473
    ##  9:   1.19326651            NaN   US 19.24684   1.268571 0.00000000
    ## 10:   0.91770446     0.88250764   US 26.70404   1.495596 0.04853710
    ## 11:   0.06825575            NaN   US 19.63017   2.617071 0.22804190
    ## 12:   0.78600982     0.21799151   US 26.33664   1.662132 0.02531829
    ## 13:   0.21882484     0.10602154   US 22.25059   2.344333 0.12615513
    ## 14:   0.84897423            NaN   US 24.72953   1.627306 0.09550599
    ## 15:   0.81129885            NaN   US 24.37799   1.653032 0.06141630
    ## 16:   0.21738934            NaN   US 21.33461   2.680875 0.04490047
    ## 17:   0.63623280            NaN   US 21.69177   1.784167 0.18435880
    ## 18:   0.63652902     0.37686248   US 21.87354   3.192539 0.09500413
    ## 19:   0.24067862     1.88911023   US 20.56798   2.568944 0.27881642
    ## 20:   0.43322758            NaN   US 18.85524   2.053283 0.09051251
    ## 21:   0.84401481            NaN   US 21.94446   1.633487 0.01610412
    ## 22:   0.57833929            NaN   US 24.89883   1.883499 0.00000000
    ## 23:   0.84579394     4.54708887   US 30.32372   3.074359 0.23342190
    ## 24:   1.40387893            NaN   US 27.14427   3.852697 0.08341749
    ## 25:   1.31360480     0.58404600   US 19.80699   3.873392 0.11063960
    ## 26:   0.98517427            NaN   US 27.87430   1.592840 0.11920878
    ## 27:   0.85693245            NaN   US 23.88844   1.895486 0.46147583
    ## 28:   0.21223614     1.37200241   US 27.57325   2.705069 0.03121757
    ## 29:   0.38223383            NaN   US 21.49638   3.098777 0.51351277
    ## 30:   0.34168629     1.05128416   US 22.02062   2.554397 0.25380753
    ## 31:   0.31323188     0.40339033   US 23.47238   2.148606 0.00000000
    ## 32:   1.10744311     0.77461602   US 24.94447   3.776083 0.20680190
    ## 33:   0.98743989     1.37635327   US 24.21220   3.680613 0.23966295
    ## 34:   1.47829033            NaN   US 18.52849   3.956459 0.18672684
    ## 35:   1.36053682     0.29379796   US 18.61379   1.408247 0.30705883
    ## 36:   0.71441147     0.03113360   US 26.69258   1.636392 0.18795706
    ## 37:   0.33532437     0.15754612   US 22.36880   2.101801 0.20806041
    ## 38:   0.13842767     0.83646713   US 24.56293   3.035050 0.48789368
    ## 39:   0.57912435     3.17006719   US 24.35182   3.145427 0.15618171
    ## 40:   1.08888409     0.40762293   US 20.35662   3.665638 0.41362317
    ## 41:   0.97842694            NaN   US 24.88657   1.576035 0.19370133
    ## 42:   0.06745468     1.54200536   US 20.40674   2.304075 0.09673718
    ## 43:   0.12163090     0.07139021   US 22.53551   2.583469 0.25853660
    ## 44:   0.31117957     0.97304128   US 21.30662   2.710944 0.12000936
    ## 45:   0.29109156     0.35441624   US 24.56026   2.752929 0.00000000
    ## 46:   0.99607217     0.85153342   US 19.55054   1.563826 0.32641573
    ## 47:   0.12459727     0.21594166   US 18.79016   2.237210 0.30721662
    ## 48:   1.98394520     0.61954666   US 19.15492   4.151737 0.43107915
    ##     wind.sp_dist atm.press_dist CTRY  temp_50 wind.sp_50     eudist

# Question 3

find the midpoint of each state

``` r
mid <- met[, .(
  lon_50 = quantile(lon, probs = 0.5, na.rm = TRUE),
  lat_50 = quantile(lat, probs = 0.5, na.rm = TRUE)
), by = STATE]
```

``` r
station_avg <- merge(
  x = station_avg,
  y = mid,
  by = "STATE"
)
```

``` r
station_avg[, mid_eudist:= sqrt(
  (lat_avg - lat_50)^2+(lon_avg - lon_50)^2
)]
station_avg
```

    ##       STATE USAFID     temp  wind.sp atm.press   lon_avg  lat_avg temp_dist
    ##    1:    AL 720265 26.22064 1.136691       NaN  -85.9630 32.91500 2.5365793
    ##    2:    AL 720307 25.14605 1.624349       NaN  -86.5570 34.86100 1.4619875
    ##    3:    AL 720361 26.62228 1.343410  1015.275  -86.3120 31.04299 2.9382239
    ##    4:    AL 720362 27.26504 1.746168  1014.559  -86.6110 31.84600 3.5809822
    ##    5:    AL 720376 24.97884 1.296044       NaN  -86.2560 34.22900 1.2947791
    ##   ---                                                                      
    ## 1591:    WY 726667 23.10219 3.290873  1012.276 -108.0820 44.51700 0.5818741
    ## 1592:    WY 726690 20.51681 4.242981  1013.000 -107.2000 41.80002 3.1672484
    ## 1593:    WY 726700 19.97665 3.066306  1015.219 -109.0163 44.51712 3.7074125
    ## 1594:    WY 726710 16.86569 3.500389  1014.944 -110.1070 42.58400 6.8183667
    ## 1595:    WY 726720 21.70287 3.800334  1012.771 -108.4569 43.06440 1.9811895
    ##       wind.sp_dist atm.press_dist CTRY  temp_50 wind.sp_50    eudist   lon_50
    ##    1:    1.3251473            NaN   US 26.33664   1.662132 0.5380938  -86.557
    ##    2:    0.8374893            NaN   US 26.33664   1.662132 1.1911908  -86.557
    ##    3:    1.1184278      0.5836496   US 26.33664   1.662132 0.4279917  -86.557
    ##    4:    0.7156699      0.1325461   US 26.33664   1.662132 0.9321989  -86.557
    ##    5:    1.1657938            NaN   US 26.33664   1.662132 1.4062861  -86.557
    ##   ---                                                                        
    ## 1591:    0.8290351      2.4150730   US 19.80699   3.873392 3.3462863 -108.389
    ## 1592:    1.7811434      1.6912827   US 19.80699   3.873392 0.8002750 -108.389
    ## 1593:    0.6044677      0.5278033   US 19.80699   3.873392 0.8247254 -108.389
    ## 1594:    1.0385507      0.2529377   US 19.80699   3.873392 2.9648557 -108.389
    ## 1595:    1.3384965      1.9200653   US 19.80699   3.873392 1.8972858 -108.389
    ##       lat_50 mid_eudist
    ##    1: 32.915  0.5940000
    ##    2: 32.915  1.9460000
    ##    3: 32.915  1.8879695
    ##    4: 32.915  1.0703630
    ##    5: 32.915  1.3480345
    ##   ---                  
    ## 1591: 42.796  1.7481667
    ## 1592: 42.796  1.5510301
    ## 1593: 42.796  1.8318759
    ## 1594: 42.796  1.7310356
    ## 1595: 42.796  0.2768643

``` r
mid_station_state <- station_avg[ , .SD[which.min(mid_eudist)], by = STATE]
mid_station_state
```

    ##     STATE USAFID     temp   wind.sp atm.press    lon_avg  lat_avg    temp_dist
    ##  1:    AL 722300 26.61913 1.4962283  1014.860  -86.78200 33.17800  2.935070321
    ##  2:    AR 723429 26.41317 1.2792990  1013.768  -93.09499 35.25800  2.729115713
    ##  3:    AZ 723745 25.47964 1.9323676       NaN -111.33900 34.25700  1.795578776
    ##  4:    CA 724815 26.37493 3.0223262  1011.292 -120.51200 37.28500  2.690874100
    ##  5:    CO 722061 13.63759 4.7152697       NaN -106.15000 39.46713 10.046469305
    ##  6:    CT 720545 22.44858 1.8953103       NaN  -72.50600 41.38400  1.235482558
    ##  7:    DE 724088 24.72840 3.0324747  1014.860  -75.46697 39.13291  1.044341502
    ##  8:    FL 721042 26.76568 2.1262635       NaN  -82.15600 28.22800  3.081616442
    ##  9:    GA 722217 26.08577 1.1111361       NaN  -82.98500 32.56400  2.401706371
    ## 10:    IA 725466 21.79148 2.7225459       NaN  -93.56600 41.69100  1.892581446
    ## 11:    ID 726810 25.03549 3.0397936  1011.730 -116.23903 43.56700  1.351435647
    ## 12:    IL 724397 22.03413 3.4911565  1015.253  -88.94836 40.48271  1.649932249
    ## 13:    IN 720961 20.94252 2.0536596       NaN  -86.37500 40.71100  2.741535659
    ## 14:    KS 724509 23.67510 4.0668332  1013.863  -97.27500 38.06763  0.008959632
    ## 15:    KY 720448 23.52994 1.6049055       NaN  -84.77000 37.57800  0.154117766
    ## 16:    LA 720468 26.89874 1.1130356       NaN  -92.09900 30.55800  3.214682905
    ## 17:    MA 725068 20.83820 1.3823436  1014.377  -71.02100 41.87600  2.845858760
    ## 18:    MD 724060 25.19890 2.5318725  1014.701  -76.68190 39.17420  1.514845149
    ## 19:    ME 726185 19.62474 2.3867047  1014.475  -69.79700 44.31612  4.059319897
    ## 20:    MI 725405 19.91292 1.9441737       NaN  -84.68800 43.32200  3.771135505
    ## 21:    MN 726583 20.84136 2.0966314       NaN  -94.50700 45.14115  2.842700394
    ## 22:    MO 724453 22.13591 3.1443238  1014.957  -93.18299 38.70400  1.548144422
    ## 23:    MS 725023 26.91719 1.5542910       NaN  -90.75800 33.85718  3.233134714
    ## 24:    MT 726798 19.47014 4.4457831  1014.072 -110.44004 45.69800  4.213915349
    ## 25:    NC 722201 24.18637 0.9103853       NaN  -79.10100 35.58208  0.502306540
    ## 26:    ND 720867 18.20367 4.2037684       NaN -100.02400 48.39000  5.480389509
    ## 27:    NE 725513 20.92713 3.1057502       NaN  -97.99681 40.89304  2.756925361
    ## 28:    NH 726050 19.86188 1.7327521  1014.487  -71.50245 43.20409  3.822183288
    ## 29:    NJ 724090 23.47238 2.1486061  1015.095  -74.35016 40.03300  0.211682876
    ## 30:    NM 722683 20.99638 3.2932303       NaN -105.51675 33.45051  2.687675870
    ## 31:    NV 724770 21.37610 3.3832432  1012.475 -116.00502 39.60100  2.307963616
    ## 32:    NY 725150 18.89641 2.7945743  1015.606  -75.98030 42.20630  4.787651548
    ## 33:    OH 720928 21.87803 2.0763441       NaN  -83.11500 40.28000  1.806032328
    ## 34:    OK 723540 26.70174 4.1168113  1013.747  -97.38319 35.41690  3.017676124
    ## 35:    OR 725975 16.97502 2.0807921  1014.410 -123.36400 42.60000  6.709034748
    ## 36:    PA 725118 24.58627 2.0405376  1015.104  -76.85100 40.21700  0.902206861
    ## 37:    RI 725074 24.45822 4.7099462       NaN  -71.41200 41.59700  0.774161791
    ## 38:    SC 720603 26.32987 1.5150567       NaN  -80.56700 34.28300  2.645809723
    ## 39:    SD 726530 21.54663 3.3501799       NaN  -99.31812 43.76696  2.137431536
    ## 40:    TN 721031 24.36992 1.5135501       NaN  -86.24600 35.38000  0.685859466
    ## 41:    TX 722570 29.78121 3.5409697  1011.429  -97.71700 31.13371  6.097152888
    ## 42:    UT 724750 27.43966 6.7110071  1011.701 -113.01225 38.42650  3.755598747
    ## 43:    VA 720498 24.92926 2.0898389  1016.447  -77.51700 37.40000  1.245200026
    ## 44:    VT 726114 17.46999 1.1657614  1014.792  -72.61400 44.53400  6.214068914
    ## 45:    WA 720388 19.35326 0.5583820       NaN -122.28683 47.10383  4.330800806
    ## 46:    WI 726465 16.59058 2.1990603       NaN  -89.66700 44.78246  7.093476632
    ## 47:    WV 720328 21.94820 1.6178231       NaN  -80.27400 39.00000  1.735861035
    ## 48:    WY 726720 21.70287 3.8003344  1012.771 -108.45695 43.06440  1.981189476
    ##     STATE USAFID     temp   wind.sp atm.press    lon_avg  lat_avg    temp_dist
    ##     wind.sp_dist atm.press_dist CTRY  temp_50 wind.sp_50     eudist   lon_50
    ##  1:   0.96560960    0.168663553   US 26.33664   1.662132 0.32760581  -86.557
    ##  2:   1.18253892    0.923584345   US 26.24296   1.938625 0.68094353  -92.767
    ##  3:   0.52947035            NaN   US 30.32372   3.074359 4.97687132 -111.733
    ##  4:   0.56048827    3.399347199   US 22.66268   2.565445 3.74026733 -120.448
    ##  5:   2.25343181            NaN   US 21.49638   3.098777 8.02332232 -105.861
    ##  6:   0.56652759            NaN   US 22.36880   2.101801 0.22136389  -72.682
    ##  7:   0.57063677    0.168362083   US 24.56026   2.752929 0.32621712  -75.467
    ##  8:   0.33557440            NaN   US 27.57325   2.705069 0.99357192  -81.876
    ##  9:   1.35070188            NaN   US 26.70404   1.495596 0.72805962  -83.270
    ## 10:   0.26070798            NaN   US 21.33461   2.680875 0.45876192  -93.566
    ## 11:   0.57795564    2.960708460   US 20.56798   2.568944 4.49226225 -116.240
    ## 12:   1.02931853    0.561879989   US 22.43194   2.237622 1.31514478  -88.751
    ## 13:   0.40817830            NaN   US 22.25059   2.344333 1.33997477  -86.296
    ## 14:   1.60499523    0.828357577   US 24.21220   3.680613 0.66154934  -97.430
    ## 15:   0.85693245            NaN   US 23.88844   1.895486 0.46147583  -84.672
    ## 16:   1.34880238            NaN   US 27.87430   1.592840 1.08716469  -91.983
    ## 17:   1.07949431    0.314400963   US 21.30662   2.710944 1.40875711  -70.918
    ## 18:   0.07003457    0.009427762   US 24.89883   1.883499 0.71444576  -76.684
    ## 19:   0.07513328    0.216045111   US 18.79016   2.237210 0.84785837  -69.667
    ## 20:   0.51766421            NaN   US 20.51970   2.273423 0.69035006  -84.688
    ## 21:   0.36520650            NaN   US 19.63017   2.617071 1.31826578  -94.382
    ## 22:   0.68248586    0.265840973   US 23.95109   2.453547 1.94217233  -93.183
    ## 23:   0.90754698            NaN   US 26.69258   1.636392 0.23914408  -90.078
    ## 24:   1.98394520    0.619546659   US 19.15492   4.151737 0.43107915 -110.440
    ## 25:   1.55145260            NaN   US 24.72953   1.627306 0.89944769  -79.101
    ## 26:   1.74193045            NaN   US 18.52849   3.956459 0.40825256  -99.621
    ## 27:   0.64391229            NaN   US 21.87354   3.192539 0.95037739  -98.054
    ## 28:   0.72908585    0.204481608   US 19.55054   1.563826 0.35421350  -71.503
    ## 29:   0.31323188    0.403390332   US 23.47238   2.148606 0.00000000  -74.417
    ## 30:   0.83139241            NaN   US 24.94447   3.776083 3.97750690 -105.990
    ## 31:   0.92140531    2.216080524   US 24.56293   3.035050 3.20580443 -116.891
    ## 32:   0.33273635    0.914842509   US 20.40674   2.304075 1.58798840  -75.412
    ## 33:   0.38549385            NaN   US 22.02062   2.554397 0.49886623  -83.078
    ## 34:   1.65497334    0.944496244   US 27.14427   3.852697 0.51536090  -97.350
    ## 35:   0.38104586    0.281202038   US 17.98061   2.011436 1.00797554 -123.364
    ## 36:   0.42130030    0.412749575   US 21.69177   1.784167 2.90582697  -76.922
    ## 37:   2.24810830            NaN   US 22.53551   2.583469 2.86683306  -71.433
    ## 38:   0.94678125            NaN   US 25.80545   1.696119 0.55479393  -80.634
    ## 39:   0.88834192            NaN   US 20.35662   3.665638 1.23111137  -99.318
    ## 40:   0.94828780            NaN   US 24.88657   1.576035 0.52041208  -86.246
    ## 41:   1.07913176    3.262240086   US 29.75188   3.413737 0.13057093  -97.691
    ## 42:   4.24916919    2.990538518   US 24.35182   3.145427 4.71679162 -113.012
    ## 43:   0.37199903    1.755508024   US 24.37799   1.653032 0.70334972  -77.558
    ## 44:   1.29607654    0.100921618   US 18.61379   1.408247 1.16922105  -72.562
    ## 45:   1.90345591            NaN   US 19.24684   1.268571 0.71811896 -122.416
    ## 46:   0.26277764            NaN   US 18.85524   2.053283 2.26934476  -89.774
    ## 47:   0.84401481            NaN   US 21.94446   1.633487 0.01610412  -80.400
    ## 48:   1.33849651    1.920065325   US 19.80699   3.873392 1.89728577 -108.389
    ##     wind.sp_dist atm.press_dist CTRY  temp_50 wind.sp_50     eudist   lon_50
    ##     lat_50   mid_eudist
    ##  1: 32.915 3.461125e-01
    ##  2: 35.333 3.364586e-01
    ##  3: 34.257 3.940000e-01
    ##  4: 36.780 5.090396e-01
    ##  5: 39.217 3.822105e-01
    ##  6: 41.384 1.760000e-01
    ##  7: 39.133 9.971146e-05
    ##  8: 28.290 2.867821e-01
    ##  9: 32.564 2.850000e-01
    ## 10: 41.717 2.600000e-02
    ## 11: 43.650 8.300893e-02
    ## 12: 40.520 2.008532e-01
    ## 13: 40.711 7.900000e-02
    ## 14: 38.329 3.038729e-01
    ## 15: 37.591 9.885848e-02
    ## 16: 30.521 1.217580e-01
    ## 17: 42.098 2.447305e-01
    ## 18: 38.981 1.932160e-01
    ## 19: 44.316 1.300001e-01
    ## 20: 43.067 2.550000e-01
    ## 21: 45.097 1.325663e-01
    ## 22: 38.583 1.210028e-01
    ## 23: 33.433 8.014541e-01
    ## 24: 45.788 8.999539e-02
    ## 25: 35.633 5.091926e-02
    ## 26: 48.301 4.127106e-01
    ## 27: 41.189 3.014369e-01
    ## 28: 43.278 7.391191e-02
    ## 29: 40.277 2.529903e-01
    ## 30: 34.067 7.771935e-01
    ## 31: 39.300 9.357129e-01
    ## 32: 42.241 5.693602e-01
    ## 33: 40.333 6.463745e-02
    ## 34: 35.534 1.217095e-01
    ## 35: 42.600 0.000000e+00
    ## 36: 40.435 2.292706e-01
    ## 37: 41.597 2.100000e-02
    ## 38: 34.181 1.220369e-01
    ## 39: 44.045 2.780388e-01
    ## 40: 35.593 2.130000e-01
    ## 41: 31.178 5.135391e-02
    ## 42: 38.427 5.594700e-04
    ## 43: 37.321 8.900562e-02
    ## 44: 44.567 6.158633e-02
    ## 45: 47.104 1.291660e-01
    ## 46: 44.614 1.995685e-01
    ## 47: 38.885 1.705902e-01
    ## 48: 42.796 2.768643e-01
    ##     lat_50   mid_eudist

merge data of median and mid stations

``` r
station_state[, type := "median"]
mid_station_state[, type := "mid"]
target_stations <- rbind(station_state, mid_station_state, fill = TRUE)
```

draw the map

``` r
library(leaflet)
pal <- colorFactor(c("Blue","DarkOrange"), domain = target_stations$type)
leaflet() %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addCircles(
    data = target_stations,
    lat = ~lat_avg, lng = ~lon_avg, 
    opacity = 1, fillOpacity = 1, radius = 400, color = ~pal(target_stations$type)
    )
```

<!--html_preserve-->

<div id="htmlwidget-b184aabe5ca78eb54e65" class="leaflet html-widget" style="width:672px;height:480px;">

</div>

<script type="application/json" data-for="htmlwidget-b184aabe5ca78eb54e65">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addProviderTiles","args":["CartoDB.Positron",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]},{"method":"addCircles","args":[[33.8126445959104,32.969,42.2669724409449,33.587,40.1999540383757,36.9,35.135,45.417,46.6827613941019,33.3550061728395,44.969,33.212,40.412,35.937,36.666,41.674,40.7682093695778,41.4337808219178,42.5420088495575,43.4172000899281,39,38.5332464285714,32.1669504405286,36.75,44.381,29.445,37.578,28.29,39.90066615266,39.84,40.033,36.744,39.0502172096909,46.9419577656676,43.344,31.1829822852081,41.7360101010101,39.417,41.196,45.443765323993,35.178,42.571,41.5329991281604,42.584,39.6740047984645,43.626,44.45,45.6980046136102,33.1779980392157,35.2580031347962,34.257,37.285,39.4671277161863,41.384,39.1329054054054,28.228,32.564,41.691,43.5669967141292,40.4827108433735,40.711,38.0676310679612,37.578,30.558,41.876,39.1742046332046,44.3161194852941,43.322,45.1411456215152,38.7040028195489,33.8571800818554,45.6980046136102,35.5820807424594,48.39,40.8930385467435,43.2040901033973,40.033,33.4505100312082,39.6009961832061,42.206297648013,40.28,35.4169039487727,42.6,40.217,41.597,34.283,43.766961247216,35.38,31.1337142857143,38.4264995948136,37.4,44.5340018796992,47.1038340767172,44.7824594594595,39,43.0643970117396],[-118.146523855891,-96.836,-84.466968503937,-80.209,-87.5998161535029,-94.017,-90.234,-123.817,-122.983,-84.5670154320988,-95.71,-87.616,-86.937,-77.547,-76.321,-93.022,-80.3981859456333,-97.3496356164383,-113.766053097345,-88.1327999100719,-80.274,-76.0328767857143,-110.883,-97.35,-106.721002247191,-90.261,-84.77,-81.437,-105.116074016962,-83.84,-74.3501562130177,-108.229,-96.7668696741855,-98.018,-72.5179990974729,-90.4710035429584,-72.6509797979798,-118.715772727273,-112.01100124533,-98.413442206655,-86.066,-77.713,-71.2829991281604,-70.917996007984,-75.6060009596929,-72.3049961389961,-68.3667746192893,-110.440038062284,-86.7820019607843,-93.0949937304075,-111.339,-120.512002560819,-106.15,-72.506,-75.4669684684685,-82.156,-82.985,-93.566,-116.239031763417,-88.9483614457831,-86.375,-97.275,-84.77,-92.099,-71.021,-76.6819034749035,-69.797,-84.688,-94.507,-93.1829934210526,-90.758,-110.440038062284,-79.101,-100.024,-97.9968072662827,-71.5024542097489,-74.3501562130177,-105.516745430227,-116.005020356234,-75.980301703163,-83.115,-97.3831921024546,-123.364,-76.851,-71.412,-80.567,-99.3181162583519,-86.246,-97.717,-113.012250202593,-77.517,-72.614,-122.286834076717,-89.667,-80.274,-108.456947705443],400,null,null,{"interactive":true,"className":"","stroke":true,"color":["#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00"],"weight":5,"opacity":1,"fill":true,"fillColor":["#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#0000FF","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00","#FF8C00"],"fillOpacity":1},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null,null]}],"limits":{"lat":[28.228,48.39],"lng":[-123.817,-68.3667746192893]}},"evals":[],"jsHooks":[]}</script>

<!--/html_preserve-->

# Question 4

``` r
met[, state_temp := mean(temp, na.rm = TRUE),by = STATE]
met[, state_wind.sp := mean(wind.sp, na.rm = TRUE),by = STATE]
met[, state_atm.press := mean(atm.press, na.rm = TRUE),by = STATE]
met[, temp_cat := fifelse(
  state_temp < 20, "low-temp", 
  fifelse(state_temp < 25, "mid-temp", "high-temp"))
  ]
```

make sure we do not have NAs

``` r
table(met$temp_cat, useNA = "always")
```

    ## 
    ## high-temp  low-temp  mid-temp      <NA> 
    ##    811126    430794   1135423         0

``` r
tab <- met[, .(
  N_entries  = .N,
  N_stations = length(unique(USAFID)),
  avg_temp = mean(state_temp),
  avg_wind.sp = mean(state_wind.sp),
  avg_atm.press = mean(state_atm.press)
), by = temp_cat]

knitr::kable(tab)
```

| temp\_cat | N\_entries | N\_stations | avg\_temp | avg\_wind.sp | avg\_atm.press |
| :-------- | ---------: | ----------: | --------: | -----------: | -------------: |
| mid-temp  |    1135423 |         781 |  22.39870 |     2.352673 |       1014.587 |
| high-temp |     811126 |         555 |  27.74436 |     2.512854 |       1013.679 |
| low-temp  |     430794 |         259 |  18.96402 |     2.642823 |             NA |
